### ISSUE TITLE
Add RPM build spec

### ISSUE THREAD

**Issue by TimothyAsir** [pcattori/namespaces#37]
In some environment or distribution pip installation is not possible. RPM build will be more helpful where we can not use pip.

**Comment by TimothyAsir** [comment]
@pcattori please review

**Comment by pcattori** [comment]
@TimothyAsir is there a reason you cannot install from source?

```sh
$ git clone https://github.com/pcattori/namespaces
$ cd namespaces
$ python setup.py install
```

**Comment by TimothyAsir** [comment]
Yes, It will be difficult for a production environment
if its a rpm package, it can be easily used / installed by another rpm.
So that it can be added as dependency in other rpm packages.
That is why, I need this feature.

**Comment by pcattori** [comment]
@TimothyAsir you will need to be more precise as to what is stopping your ability to install via the 2 supported options: either `pip install` or `python setup.py install`. What are the specific constraints in your production environment are those options not possible?

**Comment by mbukatov** [comment]
> Yes, It will be difficult for a production environment
> if its a rpm package, it can be easily used / installed by another rpm.
> So that it can be added as dependency in other rpm packages.
> That is why, I need this feature.

Based on my understanding of python packaging, maintenance of distribution specific build instruction is not a responsibility of upstream developer, but rather a job of distribution package maintainer. Upstream is responsible for setuptools based `setup.py` script, which should contain all meta data, including python dependencies.

The job of distribution packages could be simplified with this in mind: instead of writing the rpm specfile from scratch, you can have the initial specfile generated using pyp2rpm tool:

```
$ pyp2rpm namespaces 
Failed to synchronize cache for repo 'psss-edd', disabling.
# Created by pyp2rpm-3.2.1
%global pypi_name namespaces

Name:           python-%{pypi_name}
Version:        4.2.0
Release:        1%{?dist}
Summary:        Python dictionaries with items also accessible via dot-notation

License:        MIT
URL:            https://github.com/pcattori/namespaces
Source0:        https://files.pythonhosted.org/packages/source/n/%{pypi_name}/%{pypi_name}-%{version}.tar.gz
BuildArch:      noarch
 
BuildRequires:  python2-devel
BuildRequires:  python-setuptools
 
BuildRequires:  python3-devel
BuildRequires:  python3-setuptools

%description
UNKNOWN

%package -n     python2-%{pypi_name}
Summary:        Python dictionaries with items also accessible via dot-notation
%{?python_provide:%python_provide python2-%{pypi_name}}
 
Requires:       python-six >= 1.10.0
%description -n python2-%{pypi_name}
UNKNOWN

%package -n     python3-%{pypi_name}
Summary:        Python dictionaries with items also accessible via dot-notation
%{?python_provide:%python_provide python3-%{pypi_name}}
 
Requires:       python3-six >= 1.10.0
%description -n python3-%{pypi_name}
UNKNOWN


%prep
%autosetup -n %{pypi_name}-%{version}
# Remove bundled egg-info
rm -rf %{pypi_name}.egg-info

%build
%py2_build
%py3_build

%install
# Must do the subpackages' install first because the scripts in /usr/bin are
# overwritten with every setup.py install.
%py3_install

%py2_install


%check
%{__python2} setup.py test
%{__python3} setup.py test

%files -n python2-%{pypi_name}
%doc 
%{python2_sitelib}/%{pypi_name}
%{python2_sitelib}/%{pypi_name}-%{version}-py?.?.egg-info

%files -n python3-%{pypi_name}
%doc 
%{python3_sitelib}/%{pypi_name}
%{python3_sitelib}/%{pypi_name}-%{version}-py?.?.egg-info

%changelog
* Mon Feb 20 2017 Martin Bukatovic <mbukatov@redhat.com> - 4.2.0-1
- Initial package.

```

Of course, such automatically generated spec file requires human inspection and intervention, moreover some information needs to be specified by hand anyway (eg. non python dependencies), but it can still save you lot of time.

Moreover, the example showed above is the default (uses PyPI to fetch given project, and generated spec file for latest Fedora), but you can use it with sdist tarball without PyPI, specify epel7 template instead of fedora one or tweak other knobs.

@TimothyAsir So I agree with @pcattori here.
